### ISSUE TITLE
Want to contribute to IdentityServer?

### ISSUE THREAD

**Issue by leastprivilege** [Kahbazi/IdentityServer4.Contrib.LocalAccessTokenValidation#2]
Hey, 

really like your approach - want to contribute this to our core repo?

thanks!

**Comment by Kahbazi** [comment]
Hi
sure, I would love that.
Where should I add it?

**Comment by leastprivilege** [comment]
Please create a subfolder in the hosting folder. thanks!

**Comment by Kahbazi** [comment]
Ok, I will create a PR in couple of days.

**Comment by leastprivilege** [comment]
I can do it myself if you don't have the time. Just let me know.

**Comment by Kahbazi** [comment]
I like to do it myself. I will submit a PR soon.

**Comment by Kahbazi** [comment]
Should I add some options like `SaveToken` and `TokenRetriever` which exists in `IdentityServer4.AccessTokenValidation`?

In case of `TokenRetriever` I need to add `IdentityModel.AspNetCore.OAuth2Introspection` nuget package to `IdentityServer4`

**Comment by leastprivilege** [comment]
Keep it simple for now. We can add more features later.

**Comment by leastprivilege** [comment]
SaveTokens is useful though. Default to true.
