### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by garybond** [Kahbazi/IdentityServer4.Contrib.LocalAccessTokenValidation#3]
I'm having trouble getting this to work without any samples or docs.

This from my authenticated api ConfigureServices in Startup:
```csharp
services.AddAuthentication()
                    .AddLocalAccessTokenValidation(
                        options => { options.ExpectedScope = "my-scope"; });
```
This fails on authentication unable to resolve a service for ITokenValidator.
The only example of an implementation of ITokenValidator I can find is an internal class in IdentityServer4.

**Comment by Kahbazi** [comment]
I'm guessing you probably didn't Add IdentityServer to `services` since IdentityServer has the implementation of `ITokenValidator`.
By the way this library is now a built-in feature IdentityServer4 and its name is `LocalApiAuthentication`. I recommend that you use it from there.
